#pragma kernel Swizzle

RWTexture2D<float4> Source;
uint width, height;

float4 x;
float4 y;
float4 z;
float4 w;

[numthreads(8,8,1)]
void Swizzle (uint3 id : SV_DispatchThreadID)
{
	if (id.x < 0 || id.x >= width || id.y < 0 || id.y >= height)
		return;
	
	float4 color = Source[id.xy];
	
	float r = dot(color, x);
	float g = dot(color, y);
	float b = dot(color, z);
	float a = dot(color, w);
	
	Source[id.xy] = float4(r, g, b, a);
}
